### PR TITLE
fix: Remember the active type in table

### LINKED ISSUE #1059: 点击已处理的某一条，进去以后点击返回，默认进入了未处理
Screenshot from 2019-03-28 13-48-12
Screenshot from 2019-03-28 13-48-54

包括里面的”应用信息“的链接

### PR DESCRIPTION
**Pull request by whDongRui**
* fix: Hide terms of service about app info

fixed #1059

### CODE REVIEW

File: src/mixins/setPage.js [hunk 1]
```diff
@@ -23,12 +23,17 @@ function createSetPage(storeName, WrapComponent) {
...
-      const { keyword } = values;
+      const { keyword, status, activeType } = values;
       if (keyword) {
         store.searchWord = keyword;
       }
-      if (values.status) {
-        store.defaultStatus = values.status;
+
+      if (status) {
+        // store.defaultStatus = status; // todo: temporary remove
```
Comment (iwisunny) [inline src/mixins/setPage.js]: 这里改了有没有影响？
